import { screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it } from 'vitest'
import type { ProjectSummaries, TableEntry } from '../api'
import { atlas, authenticatedSession, beacon, decisionEntry, mockApi, noteEntry, renderApp } from './helpers'

const now = new Date().toISOString()
const summaries: ProjectSummaries = {
  projects: [
    { slug: 'atlas', name: 'Atlas', tier: 'focus', deadline: 'Friday', needs_me: 'Review the migration', last_entry_at: now, open_todos: 2, week_entries: 5, week_agents: ['claude-code', 'codex'], status_title: 'Deployed table page', status_body: 'long text', status_at: now, status_source: 'codex' },
    { slug: 'beacon', name: 'Beacon', tier: 'park', deadline: '', needs_me: '', open_todos: 0, week_entries: 0, week_agents: [], status_title: '', status_body: '', status_source: '' },
  ],
  metadata: { total: 10, ready: 4, failed: 0 },
}
const todo: TableEntry = {
  ...noteEntry, id: '50', kind: 'todo', body: 'We should add CSV export to the table page because phones…', source: 'codex', created_at: now, project_name: 'Atlas',
  meta: { title: 'Add CSV export', tags: ['export'], priority: 'high', refs: ['internal/admin/server.go'], origin: 'model' },
}
const doneTodo: TableEntry = { ...todo, id: '49', meta: { ...todo.meta!, title: 'Fix login', priority: 'low' }, resolved_by: { entry_id: '51', origin: 'model', created_at: now } }
const base = { 'GET /admin/api/session': authenticatedSession, 'GET /admin/api/projects': { body: { projects: [atlas, beacon] } }, 'GET /admin/api/table/projects': { body: summaries } }

describe('table', () => {
  it('opens on a per-project summary with extraction progress', async () => {
    mockApi(base)
    renderApp('/admin/table')
    const table = await screen.findByRole('table')
    const atlasRow = within(table).getAllByRole('row')[1]!
    expect(atlasRow).toHaveTextContent('Deployed table page')
    expect(atlasRow).toHaveTextContent('Needs you: Review the migration')
    expect(within(atlasRow).getByRole('link', { name: '2' })).toHaveAttribute('href', '/admin/table?view=todos&project=atlas')
    expect(within(atlasRow).getByText('codex')).toBeInTheDocument()
    expect(within(table).getAllByRole('row')[2]).toHaveTextContent('No status yet')
    expect(screen.getByText(/AI summaries: 4 of 10/)).toHaveAttribute('role', 'status')
    expect(screen.getByRole('link', { name: 'Projects', current: 'page' })).toBeInTheDocument()
  })

  it('lists open todos by priority, marks one done, and filters by tag', async () => {
    const { calls } = mockApi({
      ...base,
      'GET /admin/api/entries': (_init, url) => ({ body: { entries: url.searchParams.get('tag') === 'export' ? [todo] : [{ ...todo, id: '48', meta: { ...todo.meta!, title: 'Tidy docs', priority: 'low', tags: [] } }, todo], sources: ['codex'], tags: ['export'] } }),
      'POST /admin/api/entries/50/resolve': { status: 201, body: { ...noteEntry, kind: 'status' } },
    })
    renderApp('/admin/table?view=todos&project=atlas')
    const group = await screen.findByRole('region', { name: 'Atlas' })
    const titles = within(group).getAllByRole('button', { name: /add csv export|tidy docs/i }).map((button) => button.textContent)
    expect(titles).toEqual(['Add CSV export', 'Tidy docs'])
    const request = calls.find((call) => call.path === '/admin/api/entries')!
    expect(Object.fromEntries(request.url.searchParams)).toMatchObject({ kind: 'todo', status: 'open', project: 'atlas' })
    expect(within(group).getByText('high')).toBeInTheDocument()

    const user = userEvent.setup()
    await user.click(within(group).getByRole('button', { name: 'Add CSV export' }))
    expect(within(group).getByText(/phones…/)).toBeInTheDocument()
    expect(within(group).getByText('internal/admin/server.go')).toBeInTheDocument()
    expect(within(group).getByText(/generated by AI/)).toBeInTheDocument()

    await user.click(within(group).getAllByRole('button', { name: 'Mark done' })[0]!)
    expect(await screen.findByText('Todo marked done.')).toBeInTheDocument()
    expect(calls.find((call) => call.method === 'POST')?.init.headers).toMatchObject({ 'X-CSRF-Token': 'csrf-123' })

    await user.click(within(group).getByRole('button', { name: 'Filter by tag export' }))
    expect(await screen.findByText(/^1 row loaded/)).toBeInTheDocument()
    expect(screen.getByRole('link', { name: /download csv/i }).getAttribute('href')).toContain('tag=export')
  })

  it('shows done todos with a reopen action', async () => {
    const { calls } = mockApi({ ...base, 'GET /admin/api/entries': { body: { entries: [doneTodo], sources: [], tags: [] } }, 'POST /admin/api/entries/49/reopen': { body: { reopened: true } } })
    renderApp('/admin/table?view=todos')
    await screen.findByText('Fix login')
    await userEvent.setup().selectOptions(screen.getByRole('combobox', { name: /filter by state/i }), 'done')
    expect(screen.getByText(/Done \(detected\)/)).toBeInTheDocument()
    await userEvent.setup().click(screen.getByRole('button', { name: 'Reopen' }))
    expect(await screen.findByText('Todo reopened.')).toBeInTheDocument()
    expect(calls.some((call) => call.path === '/admin/api/entries/49/reopen')).toBe(true)
  })

  it('groups activity by day and collapses runs from one agent', async () => {
    const entries: TableEntry[] = [
      { ...decisionEntry, id: '3', source: 'codex', created_at: now, project_name: 'Atlas', meta: { title: 'Third', tags: [], refs: [], origin: 'model' } },
      { ...decisionEntry, id: '2', source: 'codex', created_at: now, project_name: 'Atlas' },
      { ...decisionEntry, id: '1', source: 'claude-code', created_at: now, project_name: 'Atlas' },
    ]
    mockApi({ ...base, 'GET /admin/api/entries': { body: { entries, sources: [], tags: [] } } })
    renderApp('/admin/table?view=activity')
    const today = await screen.findByRole('region', { name: 'Today' })
    expect(within(today).getByRole('button', { name: 'Third' })).toBeInTheDocument()
    expect(within(today).getAllByRole('button', { name: 'Use PostgreSQL <b>everywhere</b>.' })).toHaveLength(1)
    await userEvent.setup().click(within(today).getByRole('button', { name: '+1 more from codex on Atlas' }))
    expect(within(today).getAllByRole('button', { name: 'Use PostgreSQL <b>everywhere</b>.' })).toHaveLength(2)
    expect(today.querySelector('b')).toBeNull()
  })

  it('adds a row and pages older rows', async () => {
    const { calls } = mockApi({
      ...base,
      'GET /admin/api/entries': (_init, url) => ({ body: url.searchParams.get('before') === '41' ? { entries: [{ ...noteEntry, project_name: 'Atlas' }], sources: [], tags: [] } : { entries: [{ ...decisionEntry, project_name: 'Atlas' }], sources: [], tags: [], next_before: '41' } }),
      'POST /admin/api/projects/beacon/entries': { status: 201, body: { ...noteEntry, slug: 'beacon' } },
    })
    renderApp('/admin/table?view=activity')
    await screen.findByText(/1 row loaded · more available/)
    const user = userEvent.setup()
    await user.click(screen.getByRole('button', { name: /load more rows/i }))
    expect(await screen.findByText(/2 rows loaded/)).toBeInTheDocument()
    await user.click(screen.getByText('Add a row'))
    const form = screen.getByRole('form', { name: /add row/i })
    await user.selectOptions(within(form).getByRole('combobox', { name: /project/i }), 'beacon')
    await user.type(within(form).getByRole('textbox', { name: /text/i }), 'Call the vendor')
    await user.click(within(form).getByRole('button', { name: /add/i }))
    expect(await screen.findByText('Row added.')).toBeInTheDocument()
    expect(calls.find((call) => call.method === 'POST')?.body).toEqual({ kind: 'note', body: 'Call the vendor' })
  })

  it('shows an empty todo state', async () => {
    mockApi({ ...base, 'GET /admin/api/entries': { body: { entries: [], sources: [], tags: [] } } })
    renderApp('/admin/table?view=todos')
    expect(await screen.findByText('No open todos. Nice.')).toBeInTheDocument()
  })
})
